on: pull_request

name: Inspections
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: repo
#          token: ${{ secrets.ET_TOKEN }} # not needed on production but necessary for local tests.
      - name: Checkout current phpcs rules
        uses: actions/checkout@v2
        with:
          repository: elegantthemes/marketplace-phpcs
          path: rules
          token: ${{ secrets.ET_TOKEN }}
      - name: Run Inspections
        uses: poxtron/ci-review@master
        env:
          GH_BOT_TOKEN: ${{ secrets.ET_TOKEN }}

